add an option to turn off tls
thunder-app/lemmy_api_client pull request #24
Opened 2024-09-08 19:37 UTC by gwbischof

2024-09-13 23:36 UTC, gwbischof commented
Just tested this, look like its working correctly

2024-09-14 14:35 UTC, micahmo approved these changes
Nice, thanks for the simplification. This LGTM! @hjiangsu has to make the final approval.

2024-09-24 16:09 UTC, hjiangsu requested changes
Thanks again for starting work on SSO - I just have a minor comment!

2024-09-24 16:09 UTC, hjiangsu commented on lib/src/v3/main.dart
> +              scheme: (!tls && debug) ? 'http' : 'https',
I'm noticing that this line is duplicated throughout the methods. Perhaps we can move this logic up a bit? I would also add in a comment which clarifies that `tls` can only be disabled when `debug` is enabled!

For example:

```dart
String scheme = (!tls && debug) ? 'http' : 'https';

...

Uri(
    scheme: scheme,
    ...
),

2024-09-27 23:35 UTC, gwbischof commented on lib/src/v3/main.dart
> +              scheme: (!tls && debug) ? 'http' : 'https',
Updated

2024-09-29 18:51 UTC, hjiangsu approved these changes
LGTM! Thanks for making the changes

2024-09-29 18:52 UTC, merged