Add ability to retrieve taglines from site
thunder-app/lemmy_api_client pull request #3
Opened 2023-07-22 04:53 UTC by micahmo

This PR adds the ability to retrieve [Taglines](https://join-lemmy.org/api/interfaces/Tagline.html) from a Lemmy site. The goal is to show the tagline at the top of the Thunder UI (like Jerboa).

Here is an example of a tagline on [programming.dev](https://programming.dev).

| ![image](https://github.com/thunder-app/lemmy_api_client/assets/7417301/51e599da-87e5-4241-a416-ad3709ea9996) |
| - |

Here's how we can retrieve it via the API now.

``` dart
FullSiteView fullSiteView = await lemmy.run(
  GetSite(
    auth: response.jwt!.raw,
  ),
);

print(fullSiteView.taglines?.first.content);
```

And here's what the output would look like.

```
If you recently signed up (since Jul 9) and used an email, it most likely did not get saved properly. You will need to add it in your profile settings again.
```

2023-07-23 06:32 UTC, hjiangsu requested changes
Just have a few comments!

2023-07-23 06:32 UTC, hjiangsu commented on lib/src/v3/models/api.dart
> +    List<Tagline>? taglines,
This should be a required field, and if theres no taglines, it should be an empty list `[]`!

This follows the lemmy api: https://join-lemmy.org/api/interfaces/GetSiteResponse.html#taglines

2023-07-23 06:32 UTC, hjiangsu commented on lib/src/v3/models/api.dart
> +    int? id,
Everything here should be required fields as well to match up with the lemmy api: https://join-lemmy.org/api/interfaces/Tagline.html

I think the only thing missing here is the `updated` param which should be optional!

2023-07-24 02:55 UTC, micahmo commented on lib/src/v3/models/api.dart
> +    List<Tagline>? taglines,
Done.

2023-07-24 02:55 UTC, micahmo commented on lib/src/v3/models/api.dart
> +    int? id,
Done.

2023-07-24 14:36 UTC, merged

2023-07-24 14:40 UTC, micahmo commented
@hjiangsu Will you handle updating this dependency in Thunder so that the new field can be used?

2023-07-24 15:34 UTC, hjiangsu commented
Yup, I'll handle it!